# Generated by Django 5.0.6 on 2026-06-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "favorito",
            },
        ),
        migrations.CreateModel(
            name="FuenteScraping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("url_base", models.URLField()),
                ("tipo", models.CharField(max_length=50)),
                ("activa", models.BooleanField(default=True)),
                ("ultimo_scraping", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "fuente de scraping",
                "verbose_name_plural": "fuentes de scraping",
            },
        ),
        migrations.CreateModel(
            name="Licitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_expediente", models.CharField(blank=True, max_length=200)),
                ("titulo", models.CharField(max_length=500)),
                ("descripcion", models.TextField(blank=True)),
                ("organismo", models.CharField(max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("cerrada", "Cerrada"),
                            ("adjudicada", "Adjudicada"),
                            ("suspendida", "Suspendida"),
                            ("desconocido", "Desconocido"),
                        ],
                        default="desconocido",
                        max_length=30,
                    ),
                ),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
                ("fecha_apertura", models.DateField(blank=True, null=True)),
                (
                    "monto_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("url_original", models.URLField(blank=True, max_length=1000)),
                ("url_pliego", models.URLField(blank=True, max_length=1000)),
                (
                    "archivo_pliego",
                    models.FileField(blank=True, null=True, upload_to="pliegos/"),
                ),
                ("texto_ocr", models.TextField(blank=True)),
                (
                    "hash_contenido",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("provincia", models.CharField(blank=True, max_length=100)),
                ("rubro", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "licitación",
                "verbose_name_plural": "licitaciones",
                "ordering": ["-fecha_publicacion", "-created_at"],
            },
        ),
    ]
