# Generated by Django 5.0.6 on 2026-06-03 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licitaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favorito",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="licitacion",
            name="fuente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licitaciones",
                to="licitaciones.fuentescraping",
            ),
        ),
        migrations.AddField(
            model_name="favorito",
            name="licitacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritos",
                to="licitaciones.licitacion",
            ),
        ),
        migrations.AddIndex(
            model_name="licitacion",
            index=models.Index(
                fields=["estado", "fecha_apertura"],
                name="licitacione_estado_11f211_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="licitacion",
            index=models.Index(
                fields=["organismo"], name="licitacione_organis_32f266_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licitacion",
            index=models.Index(
                fields=["provincia"], name="licitacione_provinc_a82ff2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorito",
            unique_together={("usuario", "licitacion")},
        ),
    ]
