# Generated by Django 5.0.6 on 2026-06-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licitaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("corriendo", "Corriendo"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("iniciado_en", models.DateTimeField(blank=True, null=True)),
                ("finalizado_en", models.DateTimeField(blank=True, null=True)),
                ("total_encontrados", models.IntegerField(default=0)),
                ("total_nuevos", models.IntegerField(default=0)),
                ("total_duplicados", models.IntegerField(default=0)),
                ("error_mensaje", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="licitaciones.fuentescraping",
                    ),
                ),
            ],
            options={
                "verbose_name": "job de scraping",
                "ordering": ["-created_at"],
            },
        ),
    ]
