# Generated by Django 5.0.6 on 2026-06-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("palabras_clave", models.TextField(help_text="Una por línea")),
                ("provincia", models.CharField(blank=True, max_length=100)),
                ("rubro", models.CharField(blank=True, max_length=200)),
                (
                    "canal",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "alerta",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licitacion_id", models.IntegerField()),
                ("enviada_en", models.DateTimeField(auto_now_add=True)),
                ("canal", models.CharField(max_length=20)),
                ("exitosa", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
            ],
        ),
    ]
