# Generated by Django 5.0.6 on 2026-06-03 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alertas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificacionenviada",
            name="alerta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones",
                to="alertas.alerta",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificacionenviada",
            unique_together={("alerta", "licitacion_id")},
        ),
    ]
